### ISSUE TITLE
jsnlog.logger not found when using a flat file in C# site

### ISSUE THREAD

**Issue by dougeff** [mperdeck/jsnlog#87] opened 2015-11-18 23:28 UTC
Hello:

I've tried to get this setup but so far the handler doesn't seem to be working properly when I try to log something.

The site is C# 4.0 and I'm using IIS7.  NLog is working without an issue and it's version 4.2.0.  I used NuGet to install both NLog and JSNLog.  Here's the entries I have in my web.config file that the installation created:

```
<configuration xmlns="http://schemas.microsoft.com/.NetConfiguration/v2.0">
    <configSections>
        <section name="jsnlog" type="JSNLog.ConfigurationSectionHandler, JSNLog" requirePermission="false" />
        <sectionGroup name="common">
            <section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging" />
        </sectionGroup>
    </configSections>

    <system.web>
        <httpHandlers>
            <add verb="*" path="*.logger" type="JSNLog.LoggerHandler, JSNLog" />
        </httpHandlers>
    </system.web>

    <system.webServer>
        <handlers>
            <add name="LoggerHandler" verb="*" path="*.logger" type="JSNLog.LoggerHandler, JSNLog" resourceType="Unspecified" preCondition="integratedMode" />
            <add name="LoggerHandler-Classic" path="*.logger" verb="*" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll" resourceType="Unspecified" preCondition="classicMode" />
        </handlers>
    </system.webServer>

    <jsnlog productionLibraryPath="~/Scripts/jsnlog.min.js"></jsnlog>
    <common xmlns="">
        <logging>
            <factoryAdapter type="Common.Logging.NLog.NLogLoggerFactoryAdapter, Common.Logging.NLog20">
                <arg key="configType" value="INLINE" />
            </factoryAdapter>
        </logging>
    </common>
</configuration>
```

The thing to keep in mind is that the logging is going to be from a flat file, not with Webforms or MVC, so I can't call Configure.  In my HTML file, I have a reference to the main JS file:

```HTML
<script src="/Scripts/jsnlog.min.js"></script>
```

In my JS file, I make my call:

```javascript
JL().info("log message");
```

While debugging, I saw JL wasn't undefined, so that seems to be hooked up OK.  It's just when the call is executed I get this error in the browser console:

```console
POST http://local.xxx.org/jsnlog.logger 404 (Not Found)
```

The domain is mapped to 127.0.0.1 in my hosts file.  

Lastly, my application pool is using the Integrated mode.  

I feel like I'm just missing one small thing to get this all working, but I don't know what.  Please advise.  Please let me know if you need more information.  I apologize if this is more of a Visual Studio issue then an issue with your software.

Thanks for reading!

**Comment by mperdeck** [comment] 2015-11-20 04:23
Your web.config looks fine. I don't know why you're getting that 404.

Is your site hosted on local.xxx.org (that is, same domain as the logging requests)? If not, you need to add some config to your web.config for cross domain requests:
http://jsnlog.com/Documentation/GetStartedLogging/CORS

If the problem persists, could you create a minimal site that reproduces the problem and put it on Github. That will allow me to reproduce the problem at my end and find a solution.

**Comment by dougeff** [comment] 2015-11-20 21:22
Thanks for replying.  The site is hosted on the same domain as the
requests, which in this instance is my local dev machine.

I'll see what I can do about getting a mini-website up for your perusal.
I'll keep you posted.

Thanks.

**Comment by dougeff** [comment] 2015-12-18 17:33
Hi.  Finally got around to this.  I've set up a minimal website called "logtest" in my account. The error that I get in console is "Failed to load resource: the server responded with a status of 404 (Not Found)"  for "http://localhost:55305/jsnlog.logger".  Let me know if you need anything else.  Thanks for your help.

**Comment by Djerid** [comment] 2016-01-28 09:03
Hello,
i got the same error while deploying my ASP.net MVC  into IIS 7
"POST http://10.215.62.180/jsnlog.logger 404 (Not Found)"
Please help me.

thanks and regards

**Comment by mperdeck** [comment] 2016-06-11 10:39
@dougeff 

Sorry for the late response. 

I ran your logtest solution and found that indeed nothing was being logged. However, this was because NLog had not been configured in your web.config. Once I did that, it logged fine.

1) Add an nlog configsection (right above </configSections>

    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
  </configSections>

2) Add a NLog section. You could put it below the jsnlog section. The section below will create a logs directory in the root directory of your site (if it doesn't exist) and write a log file there:

  <nlog xmlns=" http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true" internalLogFile=" Nlog.txt">
    <targets>
      <target name="file" xsi:type="File" layout="${longdate} ${threadid:padding=3} ${level:padding=-30} ${logger:padding=-30} ${message} ${exception:format=tostring}" fileName="${basedir}/logs/${shortdate}.txt" />
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" writeTo="file" />
    </rules>
  </nlog>
  <common>

**Comment by mperdeck** [comment] 2016-06-11 10:44
@Djerid 

I'm closing this issue now that the problem @dougeff reported is fixed.Please open a new issue if you are still having problems. In that case, make a small solution available that lets me quickly reproduce the problem.

**Closed by mperdeck** 2016-06-11 10:44 UTC

**Comment by krishna0703** [comment] 2019-03-21 02:36
I am not able to pass client side logs to server side. I have done all suggested configurations. Please help

**Comment by ne-ShikhaManiyar** [comment] 2020-09-28 11:07
I am not able to pass client side logs to server side.
