### ISSUE TITLE
JavaScript Exception "ReferenceError: JL is not defined" when manually loading jsnlog.min.js...

### ISSUE THREAD

**Issue by icnocop** [mperdeck/jsnlog#157] opened 2017-12-15 03:34 UTC
Hi.

Thank you for JSNLog.

In an ASP.NET web application, I call `@Html.Raw(JSNLog.JavascriptLogging.Configure())` in `_Layout.html`.
However, `jsnlog.min.js` is not automatically loaded because the `productionLibraryPath` attribute in the `<jsnlog>` configuration element isn't set in web.config.

This causes a JavaScript Exception `ReferenceError: JL is not defined` in the JavaScript code generated by `@Html.Raw(JSNLog.JavascriptLogging.Configure())`:
`try { __jsnlog_configure(JL); } catch(e) {};`

In this case, `JL` is undefined and so I expected some condition checked on `JL` so that it isn't used if it hasn't been defined yet so the exception doesn't occur.

For example, `if (typeof JL !== 'undefined') { ... }`.

Thank you!

**Comment by mperdeck** [comment] 2018-01-27 03:03
Apologies for the late reply. I can't reproduce this.

I created a project where the line
try { __jsnlog_configure(JL); } catch(e) {};
gets generated by the Configure method (as you pointed out). I made sure jsnlog.min.js didn't get loaded by removing the productionLibraryPath  property from the jsnlog tag in the web.config.

This did not create a JavaScript error message in the Chrome Console, probably because the error is caught by the try catch.

Obviously, if you call JL elsewhere in your code, that will lead to a reference error.

Closing this as not reproducable. If you can still reproduce it, please send me a small app that reproduces the problem.

**Closed by mperdeck** 2018-01-27 03:03 UTC

**Comment by icnocop** [comment] 2018-01-29 19:47
Thank you.

I think this issue was caused by https://github.com/mperdeck/jsnlog.js/issues/56. I will add more details there.
