### ISSUE TITLE
'JSNLog' already has a dependency defined for 'Newtonsoft.Json'.

### ISSUE THREAD

**Issue by dilipprasad** [mperdeck/jsnlog#103] opened 2016-04-12 23:12 UTC
Getting error while installing package

Install-Package : 'JSNLog' already has a dependency defined for 'Newtonsoft.Json'.
At line:1 char:1
+ Install-Package JSNLog.Serilog -Version 2.17.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Tried to install for a empty Console app and still getting same error.

**Comment by OrtonLin** [comment] 2016-05-17 08:37
Is this issue has been fixed yet? or any workaround way to install JSNLog?

**Comment by andymartin** [comment] 2016-05-17 14:28
Also getting this error, but only on TFS builds. Local builds work fine.

**Comment by mperdeck** [comment] 2016-05-31 12:42
I couldn't reproduce this issue myself. However, after googling "already has a dependency defined for" I concluded that the issue can be resolved by upgrading to the latest version of nuget.

https://visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca
https://github.com/xunit/xunit/issues/261
https://github.com/aspnet/EntityFramework/issues/1882

I use nuget.exe 3.3.0+ and Visual Studio 2015 Community Edition. I'm not sure in which version of nuget the problem was fixed.

It doesn't seem to be a problem with the JSNLog package itself. Somebody reported this same error message whilst installing JSNLog, but I was able to install it just fine in the exact same code base with my own dev environment.

**Closed** 2016-06-07 12:24 UTC

**Comment by ocvist** [comment] 2016-06-08 16:33
I second that updating nuget may fix this issue. I ran into it before I updated nuget. After update no errors.

Visual Studio 2013 Update 5

**Comment by freeranger** [comment] 2016-06-24 13:39
@mperdeck - I get the same issue trying to push JSNLog into a local klondike nuget repository.
Upgrading the version of nuget (currently NuGet Version: 2.8.50926.602) is not an option unfortunately

**Comment by mperdeck** [comment] 2016-06-25 08:48
@freeranger 
I understand Klondike nuget repository sets out to be an enhanced version of Nuget - compatible with Nuget, but privately hosted and faster.

However, it now turns out to be no longer compatible with Nuget.

Wouldn't it make more sense to get klondike to update their system to make it compatible with Nuget again?

**Comment by freeranger** [comment] 2016-06-25 08:58
Hi,
We don't have problems with any other nugget package - and we have hundreds of them.
Indeed I have pushed JSNLog.Log4Net without any issue
Unfortunately in a corporate environment, it is not possible to insist on upgrades to nuget 3 for example - these things take a long time to be planned, approved, and executed.
